Livraison Wooc 141-146
payplug/payplug-woocommerce pull request #110
Opened 2021-02-22 15:38 UTC by jsanchez67

- [ ] Generate payplug_woocommerce.zip
- [ ] Install payplug_woocommerce.zip on your Woocommerce environment
- [ ] Login to your newly installed PayPlug plugin
- [ ] Validate a simple payment with PayPlug
- [ ] Validate a refund partial/total with PayPlug
- [ ] Check apache logs

2021-02-23 10:04 UTC, dan-payplug requested changes
Globalement, il faut changer la valeur de la constante ONEY_PRODUCT_QUANTITY_MAXIMUM = 1000 au lieu de 999

Quelques coquilles possibles également

2021-02-23 10:04 UTC, dan-payplug commented on src/Front/PayplugOneyDetail.php
> +        if ($total_price < $this->min_amount || $total_price > $this->max_amount || $total_products > PayplugGatewayOney3x::ONEY_PRODUCT_QUANTITY_MAXIMUM) {
```suggestion
        if ($total_price < $this->min_amount || $total_price > $this->max_amount || $total_products >= PayplugGatewayOney3x::ONEY_PRODUCT_QUANTITY_MAXIMUM) {
```

2021-02-23 10:04 UTC, dan-payplug commented on src/Gateway/PayplugGatewayOney3x.php
> +	const ONEY_PRODUCT_QUANTITY_MAXIMUM = 999;
```suggestion
	const ONEY_PRODUCT_QUANTITY_MAXIMUM = 1000;
```

2021-02-23 12:44 UTC, jsanchez67 commented on src/Gateway/PayplugAddressData.php
> +            $billing_company .= ' (optional)';
C'est par rapport au [Wooc-139](https://payplug-prod.atlassian.net/browse/WOOC-139) qui indique ceci:
Si le client a renseigné le champ Company Name (optional) : company_name = {Company Name (optional)}

2021-02-23 12:44 UTC, jsanchez67 commented on src/Gateway/PayplugAddressData.php
> +                    $shipping_company .= ' (optional)';
Idem du idem :)

2021-02-23 13:15 UTC, dan-payplug commented on src/Gateway/PayplugAddressData.php
> +            $billing_company .= ' (optional)';
Okay on s'est mal compris là dessus... `{Company Name (optional)}` signifiait **valeur du champ**, or le champ s'appelle  `Company Name (optional)`.

Donc en fait ce que l'on veut c'est uniquement la valeur du champ, le reste tout est okay.
Si Company Name (optional) vaut : `Quadra` on veut `Quadra` good pour toi ?

2021-02-23 13:16 UTC, dan-payplug commented on src/Gateway/PayplugAddressData.php
> +                    $shipping_company .= ' (optional)';
same

2021-02-23 13:26 UTC, jsanchez67 commented on src/Gateway/PayplugAddressData.php
> +            $billing_company .= ' (optional)';
ça marche, on s'est effectivement mal compris, je vais supprimer cette partie du coup

2021-02-23 15:25 UTC, jsanchez67 commented on assets/js/payplug-oney.js
> +                    }
C'est corrigé. (Voir la fin, le commit ne fonctionnait pas depuis ici, j'avais une erreur)

2021-02-23 15:26 UTC, jsanchez67 commented on src/Gateway/PayplugAddressData.php
> +            $billing_company .= ' (optional)';
Corrigé

2021-02-23 15:26 UTC, jsanchez67 commented on src/Gateway/PayplugGatewayOney3x.php
> +                throw new \Exception(__('The payment with Oney is unavailable because you have more than 1000 items in your cart.', 'payplug'));
La modification a été faite ainsi que la traduction

2021-02-23 17:44 UTC, dan-payplug commented
@jsanchez67 : Est ce qu'il ne manque pas la génération des fichiers de trads .mo ?

2021-02-24 10:44 UTC, dan-payplug approved these changes

2021-02-24 10:45 UTC, merged