Changement du comportement du getAccount avec un transient
payplug/payplug-woocommerce pull request #137
Opened 2021-03-23 10:52 UTC by jsanchez67

- [ ] Bump PayPlug version with a 4th digit (ex: 1.1.0 -> 1.1.0.1)
- [ ] Generate payplug_woocommerce.zip
- [ ] Install payplug_woocommerce.zip on your Woocommerce environment
- [ ] Login to your newly installed PayPlug plugin
- [ ] Validate a simple payment with PayPlug
- [ ] Validate a refund partial/total with PayPlug
- [ ] Check apache logs

2021-03-23 11:29 UTC, dan-payplug requested changes

2021-03-23 11:29 UTC, dan-payplug commented on src/Gateway/PayplugGatewayOney3x.php
> +    }
Utilisé nulle part si ?

2021-03-25 09:14 UTC, jsanchez67 commented on src/Gateway/PayplugGatewayOney3x.php
> +    }
@ThomasQuadra, tu peux répondre? 
Merci

2021-03-25 09:20 UTC, ThomasQuadra commented on src/Gateway/PayplugGatewayOney3x.php
> +    }
Non utilisé nul part, un dev qui aurait du être supprimé, vous pouvez le retirer.

2021-03-25 10:03 UTC, jsanchez67 commented on src/Gateway/PayplugGatewayOney3x.php
> +    }
```suggestion
```
A supprimer

2021-03-25 10:03 UTC, jsanchez67 commented on src/Gateway/PayplugGatewayOney3x.php
> +    }
C'est fait

2021-03-25 10:05 UTC, quadraNicolasC approved these changes
OK

2021-03-25 10:20 UTC, dan-payplug approved these changes

2021-03-25 10:21 UTC, dan-payplug approved these changes

2021-03-25 10:21 UTC, merged