PR SIM-574 / 587
payplug/payplug-woocommerce pull request #152
Opened 2021-03-31 14:36 UTC by jsanchez67

- [x ] Bump PayPlug version with a 4th digit (ex: 1.1.0 -> 1.1.0.1)
- [ x] Generate payplug_woocommerce.zip
- [ x] Install payplug_woocommerce.zip on your Woocommerce environment
- [ x] Login to your newly installed PayPlug plugin
- [ x] Validate a simple payment with PayPlug
- [ x] Validate a refund partial/total with PayPlug
- [ x] Check apache logs

2021-03-31 14:42 UTC, dan-payplug requested changes

2021-03-31 14:42 UTC, dan-payplug commented on src/Gateway/PayplugResponse.php
> +			PayplugGateway::log(sprintf('Order #%s : Order Oney IPN already in progress. Ignoring IPN', $order_id));
C'est plus lié à Oney ?
```suggestion
			PayplugGateway::log(sprintf('Order #%s : Order IPN already in progress. Ignoring IPN', $order_id));
```

2021-03-31 14:42 UTC, dan-payplug commented on src/Gateway/PayplugResponse.php
> +		$order_metadata = $order->get_meta('_payplug_metadata', true);
Est ce qu'il peut y avoir `$order_metadata` = null ?

2021-04-01 08:45 UTC, jsanchez67 commented on src/Gateway/PayplugResponse.php
> +			PayplugGateway::log(sprintf('Order #%s : Order Oney IPN already in progress. Ignoring IPN', $order_id));
Je dirai que non, @ThomasQuadra, tu peux confirmer ?

2021-04-01 08:45 UTC, jsanchez67 commented on src/Gateway/PayplugResponse.php
> +		$order_metadata = $order->get_meta('_payplug_metadata', true);
Tu peux répondre @ThomasQuadra  ?

2021-04-09 13:11 UTC, ThomasQuadra commented on src/Gateway/PayplugResponse.php
> +			PayplugGateway::log(sprintf('Order #%s : Order Oney IPN already in progress. Ignoring IPN', $order_id));
Exact oui, on peut supprimer la notion "Oney" dans le log

2021-04-12 11:59 UTC, ThomasQuadra commented on src/Gateway/PayplugResponse.php
> +		$order_metadata = $order->get_meta('_payplug_metadata', true);
Non, à chaque commande payplug les informations sont renseignés via la fonction save_transaction_metadata

2021-04-14 12:37 UTC, alopez-pp approved these changes

2021-04-14 12:39 UTC, alopez-pp commented
Pour historique: J'ai validé les demandes de Dan, je force le merge.

2021-04-14 12:39 UTC, merged