Duplications deleted
payplug/payplug-woocommerce pull request #270
Opened 2022-03-14 09:43 UTC by GhDj

- [ ] Bump PayPlug version with a 4th digit (ex: 1.1.0 -> 1.1.0.1)
- [ ] Generate payplug_woocommerce.zip
- [ ] Install payplug_woocommerce.zip on your Woocommerce environment
- [ ] Login to your newly installed PayPlug plugin
- [ ] Validate a simple payment with PayPlug
- [ ] Validate a refund partial/total with PayPlug
- [ ] Check apache logs

2022-03-14 12:13 UTC, PPmmesquita requested changes

2022-03-14 12:13 UTC, PPmmesquita commented on src/Gateway/PayplugResponse.php
>  		$order_metadata = $order->get_meta('_payplug_metadata', true);
$order_metadata - not used variable

2022-03-14 13:07 UTC, GhDj commented on src/Gateway/PayplugResponse.php
> +			if ( in_array( $resource->payment_method['type'], array( 'oney_x3_with_fees', 'oney_x4_with_fees' ) ) ) {
Yes, good point thank you

2022-03-14 13:09 UTC, GhDj commented on src/Gateway/PayplugResponse.php
> +		$metadata       = PayplugWoocommerceHelper::extract_transaction_metadata( $resource );
true I just checked that, also $order_metadata on line 58 will be removed

2022-03-14 18:41 UTC, issamhamed2020 commented
array( 'oney_x3_with_fees', 'oney_x4_with_fees' )

should have also “without fees”:

array( 'oney_x3_with_fees', 'oney_x4_with_fees', 'oney_x3_without_fees', 'oney_x4_without_fees' )

2022-03-14 18:44 UTC, issam-payplug commented
also for every check the same block of code is repeated (except $this->oney_ipn( $resource ); in the first check and $this->payplug_ipn($resource); in the second) so maybe this code can be put in a seperate function.
maybe we could let this to the refactoring later as we discussed before.

2022-03-14 18:52 UTC, issam-payplug requested changes
`array( 'oney_x3_with_fees', 'oney_x4_with_fees' )
`
should have also “without fees”:

`array( 'oney_x3_with_fees', 'oney_x4_with_fees', 'oney_x3_without_fees', 'oney_x4_without_fees' )`

2022-03-15 03:12 UTC, PPmmesquita requested changes

2022-03-15 03:12 UTC, PPmmesquita commented on src/Gateway/PayplugResponse.php
> +			if ( in_array( $resource->payment_method['type'], array( 'oney_x3_with_fees', 'oney_x4_with_fees',  'oney_x4_with_fees', 'oney_x3_without_fees', 'oney_x4_without_fees' ) ) ) {
you've "oney_x4_with_fees" twice in the array

2022-03-15 09:53 UTC, PPmmesquita approved these changes

2022-03-15 17:26 UTC, issam-payplug approved these changes

2022-03-15 17:35 UTC, merged