Evol dsp2
payplug/payplug-woocommerce pull request #72
Opened 2020-12-08 13:33 UTC by ThomasQuadra

Evol DSP2 + Mise en place du check de card oneclick existant

2020-12-17 09:15 UTC, dan-payplug requested changes

2020-12-17 09:15 UTC, ThomasQuadra commented on assets/js/payplug-checkout.js
>  /* global window, payplug_checkout_params */
Test

2020-12-17 09:28 UTC, ThomasQuadra commented on assets/js/payplug-checkout.js
> +                    }
Modif push

2020-12-17 10:57 UTC, dan-payplug requested changes

2020-12-18 08:57 UTC, Dixeat commented on assets/js/payplug-checkout.js
> +    var payplug_checkout = {
Hello, pour infos dans Github il y a une option ` Hide whitespace changes` dans la roue dentée pour rendre plus lisible la review 👍 .

2020-12-18 11:32 UTC, alopez-pp commented on src/Gateway/PayplugApi.php
> +        Payplug::init(array(
Vu qu'on utilise le init, tu peux enlever le setSecretKey juste au dessus.

2020-12-18 11:32 UTC, alopez-pp commented on src/Gateway/PayplugGateway.php
> +        wp_register_script('payplug', 'https://api-qa.payplug.com/js/1/form.latest.js', [], null, true);
Il y a l'URL de qa ⚠️ à enlever rapidement !!

2021-01-11 14:42 UTC, merged